# Generated by Django 4.0.6 on 2022-07-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi Mi?')),
                ('car_name', models.CharField(max_length=50, verbose_name='Araba Adı')),
                ('car_number_plate', models.CharField(blank=True, max_length=20, verbose_name='Araç Plakası')),
                ('cattle_capacity', models.PositiveSmallIntegerField(blank=True, max_length=100, null=True, verbose_name='Büyükbaş Kapasitesi')),
                ('ovine_capacity', models.PositiveSmallIntegerField(blank=True, max_length=200, null=True, verbose_name='Küçükbaş Kapasitesi')),
                ('is_awning', models.BooleanField(blank=True, default=False, null=True, verbose_name='Araç Tenteli Mi?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarMissionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi Mi?')),
                ('car_mission_type_name', models.CharField(max_length=50, verbose_name='Araç Görev Tip Adı')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Açıklama')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi Mi?')),
                ('car_type_name', models.CharField(max_length=50, verbose_name='Araç Tip Adı')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Araç Tip Açıklaması')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
