# Generated by Django 4.0.6 on 2022-07-13 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0003_alter_animal_cost_alter_animal_gain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi Mi?')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Hisse Açıklama')),
                ('allotment_prepay_price', models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Hisse Ön Ödeme Fiyatı')),
                ('allotment_price', models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Hisse Fiyatı')),
                ('allotment_killing_price', models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Hisse Kesim Fiyatı')),
                ('animal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_animal_of_allotment', related_query_name='q_animal_of_allotment', to='animal.animal', verbose_name='Hissenin Hayvanı')),
                ('joined_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)ss_%(class)s_related', related_query_name='%(app_label)ss_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('modified_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren Kullanıcı')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
