# Generated by Django 4.0.6 on 2022-07-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Hayvan Maliyeti'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gain',
            field=models.FloatField(default=0, verbose_name='Hayvan Karı'),
        ),
    ]
