# Generated by Django 4.0.6 on 2022-07-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='linked_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_city_of_district', related_query_name='q_city_of_district', to='address.city', verbose_name='Bağlı Şehir'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='linked_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_parish_of_district', related_query_name='q_parish_of_district', to='address.district', verbose_name='Bağlı İlçe'),
        ),
    ]
