# Generated by Django 4.0.6 on 2022-07-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_district_linked_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='address_type_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Adres Tip Adı'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ülke'),
        ),
    ]
