# Generated by Django 4.0.6 on 2022-07-12 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Adı')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Soyadı')),
                ('sex', models.CharField(blank=True, choices=[('F', 'KADIN'), ('M', 'ERKEK')], max_length=1, verbose_name='Cinsiyet')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='E-posta')),
                ('primary_phone', models.CharField(max_length=25, unique=True, verbose_name='Telefon Numarası')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi Mi?')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarihi')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_address_of_user', related_query_name='q_address_of_user', to='address.address', verbose_name='Kullanıcının Adresi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('joined_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)ss_%(class)s_related', related_query_name='%(app_label)ss_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('modified_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren Kullanıcı')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_phone_of_user', related_query_name='q_phone_of_user', to='phone.phonenumber', verbose_name='Kullanıcının Telefonu')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
