# Generated by Django 4.0.6 on 2022-07-13 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0003_alter_district_linked_city_and_more'),
        ('phone', '0002_initial'),
        ('animal', '0003_alter_animal_cost_alter_animal_gain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slaughterhouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi Mi?')),
                ('slaughterhouse_name', models.CharField(max_length=50, verbose_name='Kesimhane Adı')),
                ('description', models.CharField(max_length=250, verbose_name='Açıklama')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_address_of_slaughterhouse', related_query_name='q_address_of_slaughterhouse', to='address.address', verbose_name='Kesimhane Adresi')),
                ('joined_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)ss_%(class)s_related', related_query_name='%(app_label)ss_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('modified_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren Kullanıcı')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_phone_of_slaughterhouse', related_query_name='q_phone_of_slaughterhouse', to='phone.phonenumber', verbose_name='Kesimhane Telefonu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlaughterhouseManagerMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi Mi?')),
                ('slaughterhouse_manager_mission_type_name', models.CharField(max_length=50, verbose_name='Kesimhane Görevlisi Görev Tip Adı')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Açıklama')),
                ('joined_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)ss_%(class)s_related', related_query_name='%(app_label)ss_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('modified_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren Kullanıcı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlaughterhouseManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi Mi?')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Açıklama')),
                ('joined_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)ss_%(class)s_related', related_query_name='%(app_label)ss_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('modified_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren Kullanıcı')),
                ('slaughterhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_slaughterhouse_of_manager', related_query_name='q_slaughterhouse_of_manager', to='slaughterhouse.slaughterhouse', verbose_name='Görevliye Atanan Kesimhane')),
                ('slaughterhouse_manager_mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_mission_of_manager', related_query_name='q_mission_of_manager', to='slaughterhouse.slaughterhousemanagermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_manager_of_slaughterhouse', related_query_name='q_manager_of_slaughterhouse', to=settings.AUTH_USER_MODEL, verbose_name='Kesimhaneye Atanan Görevli')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlaughterhouseJoinType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi Mi?')),
                ('holding_capacity', models.PositiveSmallIntegerField(default=0, verbose_name='Hayvan Tutma Kapasitesi')),
                ('killing_capacity', models.PositiveSmallIntegerField(default=0, verbose_name='Aynı Anda Kesim Kapasitesi')),
                ('shredding_capacity', models.PositiveSmallIntegerField(default=0, verbose_name='Aynı Anda Parçalama Kapasitesi')),
                ('joined_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)ss_%(class)s_related', related_query_name='%(app_label)ss_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('modified_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren Kullanıcı')),
                ('slaughterhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_slaughterhouse_of_type', related_query_name='q_slaughterhouse_of_type', to='slaughterhouse.slaughterhouse', verbose_name='Kesimhane')),
                ('slaughterhouse_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_type_of_slaughterhouse', related_query_name='q_type_of_slaughterhouse', to='animal.animaltype', verbose_name='Kesimhane Tipi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
